/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pigmice.piled;

import org.junit.Test;

public class PiLEDTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        // PiLED classUnderTest = new PiLED();
        // assertTrue("someLibraryMethod should return 'true'",
        // classUnderTest.someLibraryMethod());
    }
}
