name: Build Image

on:
  push: { branches: [main] }

jobs:
  buildImage:
    name: Builds the PiLED disk image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone lights-pi-gen
        uses: actions/checkout@v2
        with:
          repository: PepperLola/lights-pi-gen
      - name: Install dependencies
        run: sudo apt-get install -y quilt qemu-user-static debootstrap zip libarchive-tools git curl grep
      - name: Setup config
        run: |
          export IMG_NAME=lights-raspian
          export RELEASE=buster
          export DEPLOY_ZIP=1
          export LOCALE_DEFAULT=en_US.UTF-8
          export TARGET_HOSTNAME=piled
          export KEYBOARD_KEYMAP=us
          export KEYBOARD_LAYOUT="English (US)"
          export TIMEZONE_DEFAULT=America/New_York
          export FIRST_USER_NAME=pi
          export ENABLE_SSH=1
          export DISABLE_FIRST_BOOT_USER_RENAME=1
      - name: Build disk image
        if: success()
        run: |
          sudo ./build.sh
      - uses: actions/upload-artifact@v1
        with:
          path: export-image/*.iso
