name: Build Image

on:
  push: { branches: [main] }

jobs:
  buildImage:
    name: Builds the PiLED disk image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone lights-pi-gen
        uses: actions/checkout@v2
        with:
          repository: PepperLola/lights-pi-gen
      - name: Install dependencies
        run: sudo apt-get install -y quilt qemu-user-static debootstrap zip libarchive-tools git curl grep
      - name: Setup config
        run: |
          echo "export IMG_NAME=lights-raspian" > config
          echo "export RELEASE=buster" > config
          echo "export DEPLOY_ZIP=1" > config
          echo "export LOCALE_DEFAULT=en_US.UTF-8" > config
          echo "export TARGET_HOSTNAME=piled" > config
          echo "export KEYBOARD_KEYMAP=us" > config
          echo "export KEYBOARD_LAYOUT='English (US)'" > config
          echo "export TIMEZONE_DEFAULT=America/New_York" > config
          echo "export FIRST_USER_NAME=pi" > config
          echo "export ENABLE_SSH=1" > config
          echo "export DISABLE_FIRST_BOOT_USER_RENAME=1" > config
      - name: Build disk image
        if: success()
        run: |
          sudo ./build.sh
      - uses: actions/upload-artifact@v1
        with:
          path: export-image/*.iso
