name: Build Image

on:
  push: { branches: [main] }

env:
  IMG_NAME: piled
  RELEASE: buster
  DEPLOY_ZIP: 1
  LOCALE_DEFAULT: en_US.UTF-8
  KEYBOARD_KEYMAP: us
  KEYBOARD_LAYOUT: English (US)
  TIMEZONE_DEFAULT: America/New_York
  FIRST_USER_NAME: pi
  ENABLE_SSH: 1
  DISABLE_FIRST_BOOT_USER_RENAME: 1

jobs:
  buildImage:
    name: Builds the PiLED disk image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone lights-pi-gen
        uses: actions/checkout@v2
        with:
          repository: PepperLola/lights-pi-gen
      - name: Install dependencies
        run: sudo apt-get install -y quilt qemu-user-static debootstrap zip libarchive-tools git curl grep
      - name: Build disk image
        if: success()
        run: |
          sudo ./build.sh
      - uses: actions/upload-artifact@v1
        with:
          path: export-image/*.iso
