name: Build Image

on:
  push: { branches: [main] }

jobs:
  buildImage:
    name: Builds the PiLED disk image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Clone lights-pi-gen
        uses: actions/checkout@v2
        with:
          repository: PepperLola/lights-pi-gen
      - name: Install dependencies
        run: sudo apt-get install -y quilt qemu-user-static debootstrap zip libarchive-tools git curl grep
      - name: Build disk image
        if: success()
        run: |
          sudo ./build.sh
      - uses: actions/upload-artifact@v1
        with:
          path: export-image/*.iso
